[package]
name = "rs256sum"
version = "0.1.0"
authors = ["Martin <rmsk2@gmx.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10"
sha2 = "0.10"
regex = "1"
clap = "4.0"