[package]
name = "rs256sum"
version = "0.1.0"
authors = ["Martin <rmsk2@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
regex = "1"
clap = "2.33.3"